 ### Frozen Lake Game

In [12]:
# %pip install numpy pandas random time gymnasium Ipyhthon matplotli

#### Imports

In [13]:
import numpy as np
import gymnasium as gym
import random
import time
import matplotlib.pyplot as plt
from IPython.display import clear_output

#### Create The Environmet

In [14]:
env = gym.make("FrozenLake-v1", render_mode="ansi")

#### Creating the Q-table

In [15]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
# print("Q-table initialized with shape:", q_table)

#### Initializing Q-learning parameters

In [16]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

#### Q-Learning Algorithm

In [23]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state, _ = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):

        #Exploration-exploitation trade-off
        exploration_threshold = random.uniform(0, 1)
        if exploration_threshold > exploration_rate:
            action = np.argmax(q_table[state])
        else:
            action = env.action_space.sample()

        new_state, reward, done, truncated, info = env.step(action)
        
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

    #Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    rewards_all_episodes.append(rewards_current_episode)

#### Calculate and Print the average reward per 1000 episodes

In [24]:
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("============== Average reward per 1000 episodes =============== ")

for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

print("============== Q-table =============== ")
print(q_table)

============== Average reward per 1000 episodes =============== 
1000 :  0.04100000000000003
2000 :  0.21700000000000016
3000 :  0.4130000000000003
4000 :  0.5400000000000004
5000 :  0.6150000000000004
6000 :  0.6720000000000005
7000 :  0.6610000000000005
8000 :  0.6840000000000005
9000 :  0.6920000000000005
10000 :  0.6880000000000005
============== Q-table =============== 
[[0.52187259 0.51623215 0.52062304 0.5196896 ]
 [0.34473083 0.30690551 0.27990282 0.51365648]
 [0.33851198 0.28713128 0.29729175 0.48806392]
 [0.10611076 0.11844831 0.11781387 0.47193583]
 [0.5367911  0.30910148 0.29321733 0.33355605]
 [0.         0.         0.         0.        ]
 [0.17397616 0.05471114 0.29262693 0.16576084]
 [0.         0.         0.         0.        ]
 [0.41881378 0.41995587 0.38139075 0.55761335]
 [0.39415479 0.61573083 0.51342499 0.32752837]
 [0.53920615 0.37839417 0.43505378 0.27576844]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.5017634